### ISSUE TITLE
Some assets are not loaded with default rewrite rules

### ISSUE THREAD

**Issue by andrerom** [ezsystems/ezplatform-demo#14]
Either assets should be moved around to bundle or we'll need to fix rewrite rules in uptream (ezplatform).

    (index):39 GET http://devdemo.ez.no/assets/images/meadow.png 404 (Not Found)
    (index):153 GET http://devdemo.ez.no/assets/images/meadow_white.png 404 (Not Found)
    (index):1 GET http://devdemo.ez.no/fonts/fontawesome-webfont.woff2?v=4.4.0 
    (index):1 GET http://devdemo.ez.no/fonts/fontawesome-webfont.woff?v=4.4.0 
    (index):1 GET http://devdemo.ez.no/fonts/fontawesome-webfont.ttf?v=4.4.0 404 (Not Found)

**Comment by clash82** [comment]
Are you using vhost delivered with ezplatform-demo?
https://github.com/ezsystems/ezplatform-demo/blob/master/doc/apache2/vhost.template#L98

**Comment by andrerom** [comment]
yse, but nginx

**Comment by andrerom** [comment]
as in https://github.com/ezsystems/ezplatform-demo/blob/master/doc/nginx/ez_params.d/ez_prod_rewrite_params

**Comment by clash82** [comment]
so the vhost for nginx must be updated too (https://github.com/ezsystems/ezplatform-demo/pull/15)

**Comment by SylvainGuittard** [comment]
Thanks @clash82
