### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by GJean** [ezsystems/ezplatform-demo#36]
Hi,

Docker compose or Dockerfile, nothing work...
When you using Docker compose, after launch all container when try localhost:8080 or localhost:8080/ez page display "File not Found"

**Comment by andrerom** [comment]
You'll need to add a bit more info, at least version number of:
- eZ Platform (version or master)
- Docker
- Docker Compsoe
- Docker for Mac or Docker Tools or Linux

**Comment by GJean** [comment]
ezPlatform : 1.4.1, 1.4.0, master
Docker : 1.12
Docker compose : 1.8
Linux

**Comment by andrerom** [comment]
Thanks, which instructions are you using? And any relevant warnings in `docker-compose logs`?

**Comment by GJean** [comment]
instructions for start : 
docker-compose -f doc/docker-compose/install.yml up --abort-on-container-exit

# Boot up full setup:
docker-compose up -d --force-recreate

and logs : 
app_1  | 172.18.0.4 -  31/Aug/2016:13:31:18 +0000 "GET app.php" 404
web_1  | 2016/08/31 13:31:18 [error] 12#12: *15 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost:8080"
web_1  | 172.18.0.1 - - [31/Aug/2016:13:31:18 +0000] "GET / HTTP/1.1" 404 27 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.117 Safari/537.36 Vivaldi/1.3.551.38" "-"
web_1  | 2016/08/31 13:31:18 [error] 12#12: *15 open() "/var/www/web/favicon.ico" failed (13: Permission denied), client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/"

**Comment by andrerom** [comment]
Hopefully found the issue, install type was not configured right for this repo, see c6fbe72.
